apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odh-chaos-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odh-chaos-controller
subjects:
  - kind: ServiceAccount
    name: odh-chaos-controller
    namespace: odh-chaos-system
